@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

MarsRover --> CompassPoint
MarsRover *-- Plateau
MissionControl *-- MarsRover
RectangularPlateau ..|> Plateau
class MissionControl {
+rover1: MarsRover
+rover2: MarsRover
}

class MarsRover {
-roverPositionX: Integer
-roverPositionY: Integer
-facingPosition: CompassPoint
-plateau: Plateau

+MarsRover(plateau:
Plateau, startPositionX: Integer, startPositionY: Integer, startFacingPosition: CompassPoint)
-turnLeft(): void
-turnRight(): void
-movesForward(): void
+move(commands: String): void
+getRoverPositionX(): Integer
+getRoverPositionY(): Integer
+geFacingPosition(): CompassPoint
+getRoverPositionAndOrientation(): String
}

Interface Plateau {
+isPlateauPositionSafeToMoveTo(positionX: Integer, positionY: Integer): boolean
}

class RectangularPlateau {
-plateauMaxSizeX: Integer
-plateauMaxSizeY: Integer
'creating a constructor here to
+Plateau(plateauMaxSizeX: Integer, plateauMaxSizeY: Integer)
+isPlateauPositionSafeToMoveTo(positionX: Integer, positionY: Integer): boolean
}

enum CompassPoint{
N,
S,
E,
W
}

@enduml